"""
Architectural Drift Detector — CLI entry point.

Usage:
  python arch_drift.py                         # scan current repo
  python arch_drift.py --pr main               # scan + diff vs main (PR mode)
  python arch_drift.py --timeline              # build full git history timeline
  python arch_drift.py --init                  # generate starter arch-rules.yml
  python arch_drift.py --show errors           # show only errors
  python arch_drift.py --threshold 30          # exit 1 if score >= threshold
  python arch_drift.py --json                  # JSON output for CI
"""

import argparse
import json
import os
import sys
import subprocess
from datetime import datetime
from pathlib import Path

from rules.loader import load_rules, find_rules_file
from scanner.git_history import (
    scan_current_state, load_previous_violations, save_violations,
    build_timeline, load_cached_timeline, save_timeline, get_current_sha
)
from reporters.html_reporter import generate_html_report
from core.models import DriftScore, DriftTimeline, ScanResult, Severity

RESET = '\033[0m'; BOLD = '\033[1m'
RED   = '\033[91m'; AMBER = '\033[93m'; BLUE = '\033[94m'; GREEN = '\033[92m'; MUTED = '\033[90m'

SEV_COLOR = {Severity.ERROR: RED, Severity.WARNING: AMBER, Severity.INFO: BLUE}


def print_violations(violations, new_ids: set):
    for v in violations:
        color = SEV_COLOR.get(v.severity, MUTED)
        new_tag = f" {RED}[NEW]{RESET}" if v.id in new_ids else ""
        print(f"  {color}[{v.severity.value.upper():7}]{RESET}  {v.message}{new_tag}")
        print(f"  {MUTED}{v.file}{':%d' % v.line if v.line else ''}{RESET}")
        if v.from_layer and v.to_layer:
            print(f"  {MUTED}{v.from_layer} → {v.to_layer}{RESET}")
        print()


def print_summary(result: ScanResult):
    s = result.drift_score
    score_color = RED if s.score >= 40 else AMBER if s.score >= 20 else GREEN
    print(f"\n{BOLD}{'─' * 60}{RESET}")
    print(f"{BOLD}  Architectural Drift Detector{RESET}  {MUTED}{datetime.now().strftime('%Y-%m-%d %H:%M')}{RESET}")
    print(f"{BOLD}{'─' * 60}{RESET}")
    print(f"  Drift score:  {score_color}{BOLD}{s.score}/100{RESET}")
    print(f"  Errors:       {RED}{s.errors}{RESET}")
    print(f"  Warnings:     {AMBER}{s.warnings}{RESET}")
    print(f"  New:          {RED}{len(result.new_violations)}{RESET}  Resolved: {GREEN}{len(result.resolved)}{RESET}")
    print(f"  Files:        {result.files_scanned}  |  Import edges: {result.import_edges}")
    if result.circular_chains:
        print(f"  {RED}Circular deps: {len(result.circular_chains)}{RESET}")
    print()


def generate_pr_comment(result: ScanResult) -> str:
    s = result.drift_score
    icon = '🔴' if s.score >= 40 else '🟡' if s.score >= 20 else '🟢'
    lines = [
        f"## Architectural Drift Detector — {icon} score {s.score}/100\n",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Drift score | **{s.score}**/100 |",
        f"| Errors | {s.errors} |",
        f"| Warnings | {s.warnings} |",
        f"| New violations | **{len(result.new_violations)}** |",
        f"| Resolved | {len(result.resolved)} |",
        f"| Files scanned | {result.files_scanned} |",
        "",
    ]
    if result.new_violations:
        lines += ["### New violations in this PR\n"]
        for v in result.new_violations[:10]:
            sev_icon = '🔴' if v.severity == Severity.ERROR else '🟡'
            lines.append(f"- {sev_icon} **{v.severity.value}** `{v.file}` — {v.message}")
        if len(result.new_violations) > 10:
            lines.append(f"- *... and {len(result.new_violations)-10} more*")
        lines.append("")

    if result.circular_chains:
        lines += ["### Circular dependencies\n"]
        for chain in result.circular_chains[:3]:
            lines.append(f"- `{'` → `'.join(chain)}`")
        lines.append("")

    lines += [
        "---",
        "*Generated by Architectural Drift Detector · Full report in Actions artifacts*"
    ]
    return '\n'.join(lines)


def cmd_init(repo_path: str):
    """Copy the starter arch-rules.yml into the repo."""
    src = Path(__file__).parent / 'arch-rules.yml'
    dst = Path(repo_path) / 'arch-rules.yml'
    if dst.exists():
        print(f"{AMBER}arch-rules.yml already exists.{RESET}")
        return
    import shutil
    shutil.copy(src, dst)
    print(f"{GREEN}✓{RESET}  Created arch-rules.yml — edit it to match your architecture.")
    print(f"  Then run: python tools/arch-drift/arch_drift.py")


def main():
    parser = argparse.ArgumentParser(prog='arch-drift', description='Architectural Drift Detector')
    parser.add_argument('--repo',      default='.', help='Repo root')
    parser.add_argument('--rules',     default='', help='Path to arch-rules.yml')
    parser.add_argument('--pr',        metavar='BRANCH', help='Diff vs base branch (PR mode)')
    parser.add_argument('--timeline',  action='store_true', help='Build git history timeline')
    parser.add_argument('--init',      action='store_true', help='Create starter arch-rules.yml')
    parser.add_argument('--show',      choices=['errors', 'warnings', 'all', 'new'], default='all')
    parser.add_argument('--threshold', type=int, default=0, help='Exit 1 if score >= threshold')
    parser.add_argument('--json',      action='store_true', help='JSON output')
    parser.add_argument('--report',    default='arch-drift-report.html', help='HTML output path')
    parser.add_argument('--no-report', action='store_true', help='Skip HTML report')
    parser.add_argument('--pr-comment',action='store_true', help='Print PR markdown comment')
    args = parser.parse_args()

    repo_path = os.path.abspath(args.repo)

    if args.init:
        cmd_init(repo_path)
        return

    # ── Load rules ─────────────────────────────────────────────────────────────
    rules_path = args.rules or find_rules_file(repo_path)
    try:
        rules = load_rules(rules_path)
        if not args.json:
            print(f"{MUTED}Rules: {rules_path}{RESET}")
    except FileNotFoundError:
        print(f"{RED}✗ No arch-rules.yml found.{RESET}")
        print(f"  Run: python arch_drift.py --init   to create one.")
        sys.exit(1)

    # ── Scan current state ─────────────────────────────────────────────────────
    prev = load_previous_violations(repo_path)
    violations, new_violations, resolved = scan_current_state(rules, repo_path, prev or None)

    # Build layer map
    from scanner.import_graph import build_import_graph
    graph = build_import_graph(repo_path)
    layers_found: dict = {}
    for node in graph.nodes.values():
        layer = rules.assign_layer(node.path)
        layers_found.setdefault(layer, []).append(node.path)

    sha = get_current_sha(repo_path)
    drift_score = DriftScore.from_violations(sha, datetime.now().strftime('%Y-%m-%d'), violations)

    result = ScanResult(
        violations=violations,
        new_violations=new_violations,
        resolved=resolved,
        drift_score=drift_score,
        files_scanned=len(graph.nodes),
        layers_found=layers_found,
        import_edges=graph.total_edges(),
        circular_chains=graph.detect_circular_chains() if rules.no_circular else [],
    )

    save_violations(violations, repo_path)

    # ── Timeline ───────────────────────────────────────────────────────────────
    timeline = None
    if args.timeline:
        if not args.json:
            print(f"{MUTED}Building drift timeline (this may take a minute)...{RESET}")
        timeline = build_timeline(rules, repo_path, rules_path, max_commits=20, verbose=not args.json)
        save_timeline(timeline, repo_path)
    else:
        timeline = load_cached_timeline(repo_path)
        if not timeline:
            timeline = DriftTimeline(repo_path=repo_path, rule_file=rules_path)
            timeline.snapshots.append(drift_score)

    # ── Output ─────────────────────────────────────────────────────────────────
    if args.json:
        data = {
            'generated': datetime.utcnow().isoformat(),
            'score': drift_score.score,
            'errors': drift_score.errors,
            'warnings': drift_score.warnings,
            'new_violations': len(new_violations),
            'resolved': len(resolved),
            'files_scanned': result.files_scanned,
            'violations': [v.to_dict() for v in violations],
        }
        print(json.dumps(data, indent=2))

    elif args.pr_comment:
        print(generate_pr_comment(result))

    else:
        print_summary(result)

        to_show = violations
        if args.show == 'errors':   to_show = [v for v in violations if v.severity == Severity.ERROR]
        if args.show == 'warnings': to_show = [v for v in violations if v.severity == Severity.WARNING]
        if args.show == 'new':      to_show = new_violations

        new_ids = {v.id for v in new_violations}
        print_violations(to_show[:30], new_ids)
        if len(to_show) > 30:
            print(f"  {MUTED}... and {len(to_show)-30} more. See HTML report.{RESET}\n")

        if not args.no_report:
            report_path = os.path.join(repo_path, args.report)
            generate_html_report(result, timeline, report_path)
            print(f"  {MUTED}Report:{RESET} file://{report_path}\n")

    # ── Exit code ──────────────────────────────────────────────────────────────
    if args.threshold > 0 and drift_score.score >= args.threshold:
        if not args.json:
            print(f"{RED}✗ Drift score {drift_score.score} ≥ threshold {args.threshold}{RESET}")
        sys.exit(1)

    sys.exit(1 if (args.pr and new_violations) else 0)


if __name__ == '__main__':
    main()
