"""
Core data models for the Assumption Miner.
An Assumption is any implicit contract in code that, if violated, causes a bug.
"""

from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Optional
import hashlib
import json


class AssumptionKind(str, Enum):
    # "this value is never null/None"
    NULL_SAFETY       = "null_safety"
    # "this list/collection always has at least one item"
    NON_EMPTY         = "non_empty"
    # "this value is within a specific numeric range"
    RANGE             = "range"
    # "this method is always called after another specific method"
    ORDERING          = "ordering"
    # "this object is always a specific subtype"
    TYPE_NARROWING    = "type_narrowing"
    # "this string always matches a specific format/pattern"
    FORMAT            = "format"
    # "this boolean condition is always true at this point"
    INVARIANT         = "invariant"
    # "// assume ...", "// always ...", "// never ..." in comments
    COMMENT_EXPLICIT  = "comment_explicit"
    # "this external service always returns X"
    EXTERNAL_CONTRACT = "external_contract"
    # "this runs only in a specific environment (timezone, locale, OS)"
    ENVIRONMENT       = "environment"


class RiskLevel(str, Enum):
    LOW      = "low"       # assumption has test coverage
    MEDIUM   = "medium"    # assumption exists but no direct test
    HIGH     = "high"      # assumption is in critical path, no test
    CRITICAL = "critical"  # assumption was recently contradicted by a PR


@dataclass
class CodeLocation:
    file: str
    line: int
    column: int = 0
    snippet: str = ""      # the actual line of code


@dataclass
class Assumption:
    # What the assumption is (human readable)
    statement: str

    # Where it lives in the code
    location: CodeLocation

    # What kind of assumption
    kind: AssumptionKind

    # The symbol this assumption is about (e.g. "userId", "OrderService.GetById")
    symbol: str

    # Confidence the detector has this is a real assumption (0.0–1.0)
    confidence: float = 0.8

    # Risk level (computed from coverage + criticality)
    risk: RiskLevel = RiskLevel.MEDIUM

    # Has a test that explicitly validates this assumption?
    has_test: bool = False

    # When was this first detected (git commit sha)
    introduced_in: str = ""

    # Unique stable ID (hash of file+line+statement)
    id: str = field(default="")

    # Any other symbols that share this assumption
    related_symbols: list[str] = field(default_factory=list)

    # If this assumption was contradicted by another part of the codebase
    contradicted_by: Optional[str] = None   # file:line of contradiction

    def __post_init__(self):
        if not self.id:
            raw = f"{self.location.file}:{self.location.line}:{self.statement}"
            self.id = hashlib.sha1(raw.encode()).hexdigest()[:12]

    def to_dict(self) -> dict:
        d = asdict(self)
        d['kind'] = self.kind.value
        d['risk'] = self.risk.value
        return d

    @classmethod
    def from_dict(cls, d: dict) -> 'Assumption':
        d['kind'] = AssumptionKind(d['kind'])
        d['risk'] = RiskLevel(d['risk'])
        d['location'] = CodeLocation(**d['location'])
        return cls(**d)


@dataclass
class ContradictionAlert:
    """Fired when a new PR introduces code that contradicts an existing assumption."""
    assumption: Assumption
    contradiction_file: str
    contradiction_line: int
    contradiction_snippet: str
    pr_number: Optional[int] = None
    severity: str = "high"

    def to_github_comment(self) -> str:
        return f"""### Assumption Miner — Contradiction Detected

**Existing assumption** in `{self.assumption.location.file}:{self.assumption.location.line}`:
> {self.assumption.statement}

**This change in `{self.contradiction_file}:{self.contradiction_line}` contradicts it:**
```
{self.contradiction_snippet.strip()}
```

**Risk:** {self.assumption.risk.value.upper()} | **Kind:** {self.assumption.kind.value}

This assumption has {'test coverage' if self.assumption.has_test else '**no test coverage**'}.
Please either update the assumption registry or add a test that validates both paths.

---
*Generated by Assumption Miner · [View full registry](./assumption-report.html)*
"""


@dataclass
class ScanResult:
    assumptions: list[Assumption]
    contradictions: list[ContradictionAlert]
    files_scanned: int
    total_assumptions: int
    by_kind: dict = field(default_factory=dict)
    by_risk: dict = field(default_factory=dict)

    def summary(self) -> str:
        crit = sum(1 for a in self.assumptions if a.risk == RiskLevel.CRITICAL)
        high = sum(1 for a in self.assumptions if a.risk == RiskLevel.HIGH)
        return (
            f"Scanned {self.files_scanned} files · "
            f"Found {self.total_assumptions} assumptions · "
            f"{crit} critical · {high} high risk · "
            f"{len(self.contradictions)} contradictions"
        )
