"""
Dead Code Analyzer — CLI entry point.

Usage:
  python dead_code.py                        # scan current repo
  python dead_code.py --repo /path/to/repo   # specific repo
  python dead_code.py --lang csharp          # filter by language
  python dead_code.py --confidence high      # only high confidence
  python dead_code.py --json                 # JSON output
  python dead_code.py --pr                   # generate cleanup PR description
  python dead_code.py --threshold 80         # exit 1 if score > threshold
  python dead_code.py --no-graph             # skip reachability (faster, less accurate)
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

from scanner.symbol_extractor import scan_all_symbols
from graph.reference_graph import build_reference_map, find_entry_points, build_call_graph, reachability_bfs
from graph.confidence_scorer import classify_dead_symbols, build_scan_result
from reporters.html_reporter import generate_html_report
from core.models import Confidence, ScanResult

RESET = '\033[0m'; BOLD = '\033[1m'
RED   = '\033[91m'; AMBER = '\033[93m'; BLUE = '\033[94m'; GREEN = '\033[92m'; MUTED = '\033[90m'

CONF_COLOR = {Confidence.HIGH: RED, Confidence.MEDIUM: AMBER, Confidence.LOW: BLUE}


def print_summary(result: ScanResult):
    h = result.by_confidence.get('high', 0)
    m = result.by_confidence.get('medium', 0)
    print(f"\n{BOLD}{'─'*60}{RESET}")
    print(f"{BOLD}  Dead Code Analyzer{RESET}  {MUTED}{datetime.now().strftime('%Y-%m-%d %H:%M')}{RESET}")
    print(f"{'─'*60}")
    print(f"  Files scanned:      {result.files_scanned}")
    print(f"  Symbols found:      {result.symbols_found}")
    print(f"  Dead found:         {result.dead_count}")
    print(f"  High confidence:    {RED}{h}{RESET}  (safe to delete)")
    print(f"  Medium confidence:  {AMBER}{m}{RESET}  (investigate)")
    print(f"  Recoverable LOC:    ~{result.lines_recoverable}")
    print()


def print_dead(result: ScanResult, limit: int = 30, min_conf: str = 'medium'):
    order = ['high', 'medium', 'low']
    min_idx = order.index(min_conf)
    items = [d for d in result.dead_symbols if order.index(d.confidence.value) <= min_idx]

    for d in items[:limit]:
        color = CONF_COLOR.get(d.confidence, MUTED)
        safe = f"  {GREEN}[safe to delete]{RESET}" if d.safe_to_delete else ""
        print(f"  {color}[{d.confidence.value.upper():6} {d.confidence_pct:3}%]{RESET}  {d.symbol.kind.value:9}  {d.symbol.name}{safe}")
        print(f"  {MUTED}{d.symbol.file}:{d.symbol.line}{RESET}")
        print(f"  {d.explanation}")
        if d.suppressions:
            print(f"  {AMBER}Caution: {d.suppressions[0]}{RESET}")
        print()

    if len(items) > limit:
        print(f"  {MUTED}... {len(items)-limit} more. See HTML report.{RESET}\n")


def generate_pr_description(result: ScanResult) -> str:
    high = [d for d in result.dead_symbols if d.confidence == Confidence.HIGH and d.safe_to_delete]
    lines = [
        "## Dead code cleanup\n",
        f"Removes {len(high)} dead symbols identified by the Dead Code Analyzer "
        f"(HIGH confidence, safe to delete).\n",
        f"Estimated LOC removed: ~{sum(d.symbol.lines_of_code for d in high)}\n",
        "### Symbols removed\n",
    ]
    for d in high[:30]:
        lines.append(f"- `{d.symbol.name}` ({d.symbol.kind.value}) in `{d.symbol.file}:{d.symbol.line}`")
    if len(high) > 30:
        lines.append(f"- *...and {len(high)-30} more*")
    lines += [
        "\n---",
        f"*Generated by Dead Code Analyzer · {datetime.now().strftime('%Y-%m-%d')}*"
    ]
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(prog='dead-code', description='Dead Code Analyzer')
    parser.add_argument('--repo',       default='.', help='Repo root path')
    parser.add_argument('--lang',       choices=['csharp','java','angular','all'], default='all')
    parser.add_argument('--confidence', choices=['high','medium','low'], default='medium')
    parser.add_argument('--min-pct',    type=int, default=60, help='Minimum confidence %')
    parser.add_argument('--no-graph',   action='store_true', help='Skip call graph (faster)')
    parser.add_argument('--json',       action='store_true', help='JSON output')
    parser.add_argument('--pr',         action='store_true', help='Print cleanup PR description')
    parser.add_argument('--report',     default='dead-code-report.html')
    parser.add_argument('--no-report',  action='store_true')
    parser.add_argument('--threshold',  type=int, default=0, help='Exit 1 if dead_count >= threshold')
    args = parser.parse_args()

    repo_path = os.path.abspath(args.repo)
    verbose   = not args.json

    # ── Scan symbols ───────────────────────────────────────────────────────────
    if verbose:
        print(f"\n{BOLD}Dead Code Analyzer{RESET}  {MUTED}{repo_path}{RESET}")
        print(f"{MUTED}Scanning symbols...{RESET}")

    symbols, file_count = scan_all_symbols(repo_path, verbose=verbose)

    if args.lang != 'all':
        symbols = [s for s in symbols if s.language == args.lang]

    if verbose:
        print(f"  {len(symbols)} symbols found in {file_count} files")

    # ── Reference scan ─────────────────────────────────────────────────────────
    if verbose:
        print(f"{MUTED}Scanning references...{RESET}")

    ref_counts = build_reference_map(symbols, repo_path, verbose=verbose)

    # ── Reachability ───────────────────────────────────────────────────────────
    reachable_ids: set[str] = set()
    if not args.no_graph:
        if verbose:
            print(f"{MUTED}Building call graph + reachability...{RESET}")
        entry_ids  = find_entry_points(symbols, repo_path)
        call_graph = build_call_graph(symbols, repo_path)
        reachable_ids = reachability_bfs(entry_ids, call_graph)
        if verbose:
            print(f"  Entry points: {len(entry_ids)}  Reachable: {len(reachable_ids)}")

    # ── Classify ───────────────────────────────────────────────────────────────
    if verbose:
        print(f"{MUTED}Classifying dead symbols...{RESET}")

    dead = classify_dead_symbols(
        symbols, ref_counts, reachable_ids, repo_path,
        min_confidence=args.min_pct
    )
    result = build_scan_result(dead, file_count, len(symbols))

    # ── Output ─────────────────────────────────────────────────────────────────
    if args.json:
        data = {
            'generated': datetime.utcnow().isoformat(),
            'files_scanned': file_count,
            'symbols_found': len(symbols),
            'dead_count': len(dead),
            'safe_to_delete': result.safe_to_delete,
            'lines_recoverable': result.lines_recoverable,
            'by_confidence': result.by_confidence,
            'dead_symbols': [d.to_dict() for d in dead],
        }
        print(json.dumps(data, indent=2))

    elif args.pr:
        print(generate_pr_description(result))

    else:
        print_summary(result)
        print_dead(result, limit=20, min_conf=args.confidence)

        if not args.no_report:
            report_path = os.path.join(repo_path, args.report)
            generate_html_report(result, report_path)
            print(f"  {MUTED}Report:{RESET} file://{report_path}\n")

    # ── Exit code ──────────────────────────────────────────────────────────────
    if args.threshold > 0 and len(dead) >= args.threshold:
        sys.exit(1)


if __name__ == '__main__':
    main()
