"""
Core data models for Cross-PR Dependency Intelligence.

The central insight: PRs are not independent. Before they merge,
we need to know which ones are stepping on each other's work.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional
import hashlib


class OverlapKind(str, Enum):
    LINE_COLLISION   = "line_collision"    # two PRs edit the exact same lines
    SYMBOL_CONFLICT  = "symbol_conflict"   # two PRs modify the same function/class
    SEMANTIC_DEP     = "semantic_dep"      # PR A calls a function that PR B is changing
    SHARED_FILE      = "shared_file"       # both PRs touch the same file (lower confidence)
    IMPORT_CHAIN     = "import_chain"      # PR A imports from something PR B is restructuring


class Severity(str, Enum):
    CRITICAL = "critical"   # guaranteed merge conflict
    HIGH     = "high"       # very likely semantic breakage
    MEDIUM   = "medium"     # worth communicating, may be intentional
    LOW      = "low"        # awareness only


@dataclass
class FileChange:
    """A single file changed in a PR, with line-range metadata."""
    path:          str
    status:        str          # 'modified', 'added', 'deleted', 'renamed'
    additions:     int
    deletions:     int
    changed_lines: list[tuple[int, int]] = field(default_factory=list)  # [(start, end), ...]
    old_path:      str = ""     # populated for renames


@dataclass
class SymbolChange:
    """A code symbol (method, class, function) changed in a PR."""
    name:          str
    kind:          str          # 'method', 'class', 'function', 'component', 'interface'
    file:          str
    line_start:    int
    line_end:      int
    change_type:   str          # 'modified', 'added', 'deleted'
    language:      str


@dataclass
class PRSnapshot:
    """Everything we know about one open PR."""
    number:        int
    title:         str
    author:        str
    branch:        str
    base_branch:   str
    url:           str
    state:         str          # 'open', 'draft', 'review_requested'
    created_at:    str
    updated_at:    str
    changed_files: list[FileChange]  = field(default_factory=list)
    symbols:       list[SymbolChange] = field(default_factory=list)
    raw_diff:      str = ""

    def file_paths(self) -> set[str]:
        return {f.path for f in self.changed_files}

    def symbol_names(self) -> set[str]:
        return {s.name for s in self.symbols}


@dataclass
class Overlap:
    """A detected overlap between two PRs."""
    pr_a:          int          # PR number
    pr_b:          int          # PR number
    kind:          OverlapKind
    severity:      Severity
    description:   str          # human-readable explanation
    file:          str          # which file the overlap is in
    symbol:        str = ""     # which symbol (if applicable)
    line_range_a:  Optional[tuple[int,int]] = None
    line_range_b:  Optional[tuple[int,int]] = None
    merge_order_matters: bool = False   # True = merging A before B changes the outcome

    # Stable ID for deduplication
    id: str = field(default="")

    def __post_init__(self):
        if not self.id:
            raw = f"{min(self.pr_a,self.pr_b)}:{max(self.pr_a,self.pr_b)}:{self.file}:{self.symbol}:{self.kind}"
            self.id = hashlib.sha1(raw.encode()).hexdigest()[:10]

    def to_dict(self) -> dict:
        return {
            'id':            self.id,
            'pr_a':          self.pr_a,
            'pr_b':          self.pr_b,
            'kind':          self.kind.value,
            'severity':      self.severity.value,
            'description':   self.description,
            'file':          self.file,
            'symbol':        self.symbol,
            'merge_order':   self.merge_order_matters,
        }


@dataclass
class ConflictReport:
    """Full report for one PR — what it conflicts with and why."""
    pr:                PRSnapshot
    overlaps:          list[Overlap]
    affected_prs:      list[int]      # distinct PR numbers this PR conflicts with
    severity_summary:  dict           # {'critical': 2, 'high': 1, ...}
    recommendation:    str            # plain-English action recommendation

    def has_critical(self) -> bool:
        return any(o.severity == Severity.CRITICAL for o in self.overlaps)

    def to_github_comment(self, all_prs: dict[int, PRSnapshot]) -> str:
        if not self.overlaps:
            return (
                f"## Cross-PR Intelligence — PR #{self.pr.number}\n\n"
                f"No conflicts with other open PRs detected.\n\n"
                f"*Generated by Cross-PR Dependency Intelligence*"
            )

        icon = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}
        top_sev = "critical" if self.severity_summary.get("critical", 0) > 0 \
             else "high" if self.severity_summary.get("high", 0) > 0 \
             else "medium"

        lines = [
            f"## Cross-PR Intelligence — {icon[top_sev]} conflicts detected\n",
            f"This PR overlaps with **{len(self.affected_prs)}** other open PR(s).\n",
            f"| Severity | Count |",
            f"|----------|-------|",
        ]
        for sev in ["critical", "high", "medium", "low"]:
            count = self.severity_summary.get(sev, 0)
            if count:
                lines.append(f"| {icon[sev]} {sev.title()} | {count} |")

        lines.append(f"\n### Conflicts\n")
        for overlap in sorted(self.overlaps, key=lambda o: ["critical","high","medium","low"].index(o.severity.value)):
            other = all_prs.get(overlap.pr_b if overlap.pr_a == self.pr.number else overlap.pr_a)
            other_str = f"PR #{other.number} ({other.title[:40]})" if other else f"PR #{overlap.pr_b}"
            lines.append(f"- {icon[overlap.severity.value]} **{overlap.kind.value.replace('_',' ').title()}** with {other_str}")
            lines.append(f"  - File: `{overlap.file}`" + (f" · Symbol: `{overlap.symbol}`" if overlap.symbol else ""))
            lines.append(f"  - {overlap.description}")
            if overlap.merge_order_matters:
                lines.append(f"  - **Merge order matters** — coordinate with that PR's author")
            lines.append("")

        lines += [
            f"### Recommendation\n",
            self.recommendation,
            "\n---",
            "*Generated by Cross-PR Dependency Intelligence*"
        ]
        return '\n'.join(lines)
