const vscode = require('vscode');
const path = require('path');
const fs = require('fs');
const { registerChatParticipant } = require('./src/chatParticipant');
const { registerCodeToDigram } = require('./src/codeToDiagram');
const { registerADR, stabilizeDiagramJSON } = require('./src/adr');
const { registerLiveSync } = require('./src/liveSync');

let panel = null;
let liveSyncApi = null;

function activate(context) {

  // ── Command: Open Flow Builder ──
  const openCmd = vscode.commands.registerCommand('flowbuilder.open', (uri) => {
    openPanel(context, uri);
  });

  const openSideCmd = vscode.commands.registerCommand('flowbuilder.openInSide', (uri) => {
    openPanel(context, uri, vscode.ViewColumn.Beside);
  });

  context.subscriptions.push(openCmd, openSideCmd);

  const getPanel = () => panel;

  // Phase 1 — Copilot Chat participant (@flowbuilder)
  registerChatParticipant(context, getPanel);

  // Phase 2 — ADR scaffolding
  registerADR(context);

  // Phase 3 — Code-to-diagram via Copilot
  registerCodeToDigram(context, getPanel);

  // Phase 5 — Live sync: CodeLens + refresh-from-source (also covers embedded-open command)
  liveSyncApi = registerLiveSync(context, getPanel);
}

function openPanel(context, fileUri, column) {
  column = column || vscode.ViewColumn.One;

  // Reuse existing panel if open
  if (panel) {
    panel.reveal(column);
    if (fileUri) loadFileIntoPanel(fileUri);
    return;
  }

  // Create WebView panel
  panel = vscode.window.createWebviewPanel(
    'flowbuilder',
    'Flow Builder',
    column,
    {
      enableScripts: true,
      retainContextWhenHidden: true, // keep diagram alive when switching tabs
      localResourceRoots: [
        vscode.Uri.joinPath(context.extensionUri, 'media')
      ]
    }
  );

  // Load the HTML
  const htmlPath = path.join(context.extensionPath, 'media', 'flowbuilder.html');
  let html = fs.readFileSync(htmlPath, 'utf8');

  // Inject VS Code API bridge before closing </body>
  const bridge = `
<script>
// ── VS Code Bridge ──
const vscodeApi = acquireVsCodeApi();

// Override export buttons to also offer "Save to workspace"
window.__vscode = {
  saveToWorkspace: function(data, filename) {
    vscodeApi.postMessage({ command: 'saveFile', data, filename });
  },
  insertSVG: function(svg) {
    vscodeApi.postMessage({ command: 'insertSVG', svg });
  },
  showInfo: function(msg) {
    vscodeApi.postMessage({ command: 'info', text: msg });
  }
};

// Receive messages from extension host
window.addEventListener('message', event => {
  const msg = event.data;
  if (msg.command === 'loadDiagram' && msg.json) {
    try {
      const state = JSON.parse(msg.json);
      if (window.__flowAPI) window.__flowAPI.loadDiagramJSON(state);
      toast('Diagram loaded from ' + msg.filename);
    } catch(e) { console.error('Load error', e); }
  }
  if (msg.command === 'loadDSL' && msg.text) {
    try {
      if (window.__flowAPI) window.__flowAPI.loadMermaid(msg.text);
      toast(msg.sourceMeta ? 'Diagram generated from code' : 'Diagram generated by Copilot');
      if (msg.sourceMeta) {
        vscodeApi.postMessage({ command: 'trackSource', file: msg.sourceMeta.file });
      }
    } catch(e) { console.error('DSL load error', e); }
  }
});
</script>`;

  html = html.replace('</body>', bridge + '\n</body>');
  panel.webview.html = html;

  // ── Handle messages from WebView ──
  panel.webview.onDidReceiveMessage(async msg => {
   try {

    if (msg.command === 'saveFile') {
      // Save diagram JSON to workspace
      const workspaceFolders = vscode.workspace.workspaceFolders;
      if (!workspaceFolders) {
        vscode.window.showErrorMessage('Open a workspace folder first.');
        return;
      }
      const defaultUri = vscode.Uri.joinPath(
        workspaceFolders[0].uri,
        msg.filename || 'diagram.flow'
      );
      const uri = await vscode.window.showSaveDialog({
        defaultUri,
        filters: {
          'Flow Diagram': ['flow'],
          'SVG': ['svg'],
          'PNG': ['png']
        }
      });
      if (uri) {
        let content;
        if (uri.fsPath.endsWith('.flow') && msg.dataIsJSON) {
          // Phase 2: sort nodes/edges for diff-friendly git history
          try {
            const obj = JSON.parse(Buffer.from(msg.data, 'base64').toString('utf8'));
            const stable = stabilizeDiagramJSON(obj);
            content = Buffer.from(JSON.stringify(stable, null, 2), 'utf8');
          } catch (e) {
            content = Buffer.from(msg.data, 'base64');
          }
        } else {
          content = Buffer.from(msg.data, 'base64');
        }
        try {
          await vscode.workspace.fs.writeFile(uri, content);
          vscode.window.showInformationMessage(`Saved: ${path.basename(uri.fsPath)}`);
        } catch (writeErr) {
          vscode.window.showErrorMessage(`Could not save file: ${writeErr.message}`);
        }
      }
    }

    if (msg.command === 'insertSVG') {
      // Insert SVG at cursor in active editor
      const editor = vscode.window.activeTextEditor;
      if (!editor) {
        vscode.window.showWarningMessage('No active editor to insert SVG into.');
        return;
      }
      try {
        const ok = await editor.edit(editBuilder => {
          editBuilder.insert(editor.selection.active, msg.svg);
        });
        if (ok) {
          vscode.window.showInformationMessage('SVG inserted at cursor.');
        } else {
          vscode.window.showWarningMessage('Could not insert SVG — editor may be read-only.');
        }
      } catch (editErr) {
        vscode.window.showErrorMessage(`Insert failed: ${editErr.message}`);
      }
    }

    if (msg.command === 'info') {
      vscode.window.showInformationMessage(msg.text);
    }

    if (msg.command === 'trackSource' && msg.file && liveSyncApi) {
      // Phase 5: watch this source file for changes to prompt diagram refresh
      liveSyncApi.trackSource(msg.file);
    }

   } catch (unexpectedErr) {
     console.error('flowbuilder: unhandled message error', unexpectedErr);
     vscode.window.showErrorMessage(`Flow Builder error: ${unexpectedErr.message}`);
   }
  }, undefined, context.subscriptions);

  // Load file if opened via .flow file
  if (fileUri) loadFileIntoPanel(fileUri);

  // Cleanup on close
  panel.onDidDispose(() => { panel = null; }, null, context.subscriptions);
}

async function loadFileIntoPanel(uri) {
  if (!panel) return;
  try {
    const bytes = await vscode.workspace.fs.readFile(uri);
    const json = Buffer.from(bytes).toString('utf8');
    const filename = path.basename(uri.fsPath);
    panel.webview.postMessage({ command: 'loadDiagram', json, filename });
  } catch (e) {
    vscode.window.showErrorMessage('Could not load diagram: ' + e.message);
  }
}

function deactivate() {}

module.exports = { activate, deactivate };
